version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - room_service
      - reservation_service
      - user_service
    networks:
      - app_network
    environment:
      - ROOM_SERVICE_URL=http://room_service:5002
      - RESERVATION_SERVICE_URL=http://reservation_service:5003
      - USER_SERVICE_URL=http://user_service:5001

  room_service:
    build:
      context: ./room_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks:
      - app_network
    environment:
      - ROOM_SERVICE_URL=http://room_service:5002

  reservation_service:
    build:
      context: ./reservation_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    networks:
      - app_network
    environment:
      - RESERVATION_SERVICE_URL=http://reservation_service:5003

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app_network
    environment:
      - USER_SERVICE_URL=http://user_service:5001

networks:
  app_network:
    driver: bridge
